name: Deploy

on:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - run: |
                  echo Please run it from the "site" branch.
                  exit 1
